name: mpflutter_flutter_template
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  bot_toast: ^4.0.3
  
  flutter:
    sdk: flutter
  
  # image_editor_plus: ^0.2.0

  image_picker: ^0.8.7+1
  mp_flutter_runtime: 
    path: /Users/sondhoang/DevelopWorkSpace/mbbank/mbbank-multiple-feature/rdmbflutter/mbflutter/packages/mp_flutter_runtime

  mp_switch_runtime:
    path: /Users/sondhoang/DevelopWorkSpace/mbbank/mbbank-multiple-feature/rdmbflutter/mbflutter/packages/mp_switch_runtime

  mp_lottie_runtime:
    path: /Users/sondhoang/DevelopWorkSpace/mbbank/mbbank-multiple-feature/rdmbflutter/mbflutter/packages/mp_lottie_runtime

  path_provider: ^2.0.13




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets: 
    - assets/
    